### PR TITLE
Exception

### LINKED ISSUE #11: Add Custom Exceptions
Add at least three custom exceptions

### PR DESCRIPTION
**Pull request by FelixJacobsen**
Fix #11 

Includes three custom exceptions. MethodNotAllowed exception needs to be implemented after update methods have been created in all controller and service classes.

### CODE REVIEW

**Comment by helenahalldiniths** [comment]
I accedently markt this as ready for review, my bad!

**Review by helenahalldiniths — CHANGES_REQUESTED** [review]
I have looked throught the code and it looks good. However, the Victim-class is missing som error handling

**Comment by helenahalldiniths** [comment]
I think this is ok! I will look at the "exceptions" videos when I get a chance and after that I can do a final review!

**Review by helenahalldiniths — APPROVED** [review]
I've made some small changes, but overall it looks good. 
My only thaught is that maybe we shouldn't throw an exception when "findAll" returns an empty list? If there are no entitys an empty list is a correct response! What do you think?

**Comment by helenahalldiniths** [comment]
Tips on inprovment later on:

In GlobalExceptionHandler:
- Override some of the methods that already exists (handleHttpMessageNotReadable, handleHttpRequestMethodNotSupported…). 

- Implement a ”handleAll” method that handels all errors that are not handled by any other.

**Comment by LordRekishi** [comment]
> Tips on inprovment later on:
> 
> In GlobalExceptionHandler:
> 
> * Override some of the methods that already exists (handleHttpMessageNotReadable, handleHttpRequestMethodNotSupported…).
> * Implement a ”handleAll” method that handels all errors that are not handled by any other.

Sounds good. You making some "enhancement" issues and putting them further down the line?

File: src/main/java/se/iths/crimedatabase/controller/AddressController.java [hunk 1]
```diff
@@ -19,36 +22,51 @@ public AddressController(AddressService addressService) {
 
     @PostMapping
     public ResponseEntity<Address> create(@RequestBody Address address) {
```
Comment (LordRekishi) [inline src/main/java/se/iths/crimedatabase/controller/AddressController.java:24]: Suggestion for this from the Java EE part of the course is to use ConstraintViolation and a javax.validation.Validator or something similar for Spring. That way we avoid these .isEmpty and isEmpty and so on. Anyone checked out anything similar for Spring?

File: src/main/java/se/iths/crimedatabase/controller/AddressController.java [hunk 2]
```diff
@@ -19,36 +22,51 @@ public AddressController(AddressService addressService) {
...
+        if (address.getStreetAddress().isEmpty() || address.getCity().isEmpty() || address.getZipCode().isEmpty())
+            throw new BadRequestException("Street address, city and zipcode cannot be empty");
+
         Address createdAddress = addressService.create(address);
         return new ResponseEntity<>(createdAddress, HttpStatus.CREATED);
     }
 
     @DeleteMapping("{id}")
     public ResponseEntity<Void> delete(@PathVariable Long id) {
+        if (addressService.findById(id).isEmpty())
```
Comment (LordRekishi) [inline src/main/java/se/iths/crimedatabase/controller/AddressController.java:34]: We talked about this quite a bit on Martin's lectures. I think the agreement was to send a Response.OK if the entity could not be found since this also means the entity is "deleted" (not existing to begin with) and the function is successfull.

File: src/main/java/se/iths/crimedatabase/controller/AddressController.java [hunk 3]
```diff
@@ -19,36 +22,51 @@ public AddressController(AddressService addressService) {
...
+            throw new NotFoundException(notFoundMessage(id));
+
         Optional<Address> foundAddress = addressService.findById(id);
         return new ResponseEntity<>(foundAddress, HttpStatus.OK);
     }
 
     @GetMapping
     public ResponseEntity<Iterable<Address>> findAll() {
         Iterable<Address> addresses = addressService.findAll();
+        if (!addresses.iterator().hasNext())
```
Comment (LordRekishi) [inline src/main/java/se/iths/crimedatabase/controller/AddressController.java:53]: Either we have this error or just return an empty json? I guess the error is better for clarity?

**Review by LordRekishi — CHANGES_REQUESTED** [review]
I just made comments on Address, but it applies to all controllers.

File: src/main/java/se/iths/crimedatabase/controller/AddressController.java (hunk 3 above)
Comment (FelixJacobsen) [reply src/main/java/se/iths/crimedatabase/controller/AddressController.java:53]: To me a empty json is more confusing but if you're in agreement that it's better I'm down to change

File: src/main/java/se/iths/crimedatabase/controller/AddressController.java (hunk 1 above)
Comment (FelixJacobsen) [reply src/main/java/se/iths/crimedatabase/controller/AddressController.java:24]: I know there is a @Valid annotation however I think we should make this as an enchantment.

File: src/main/java/se/iths/crimedatabase/controller/AddressController.java (hunk 2 above)
Comment (FelixJacobsen) [reply src/main/java/se/iths/crimedatabase/controller/AddressController.java:34]: This does not work in Spring, it will return a 500 Internal Server Errror
image

File: src/main/java/se/iths/crimedatabase/controller/AddressController.java (hunk 1 above)
Comment (LordRekishi) [reply src/main/java/se/iths/crimedatabase/controller/AddressController.java:24]: Agreed!

File: src/main/java/se/iths/crimedatabase/controller/AddressController.java (hunk 2 above)
Comment (LordRekishi) [reply src/main/java/se/iths/crimedatabase/controller/AddressController.java:34]: Ok!

File: src/main/java/se/iths/crimedatabase/controller/AddressController.java (hunk 3 above)
Comment (LordRekishi) [reply src/main/java/se/iths/crimedatabase/controller/AddressController.java:53]: Will the program shut down when an exception is thrown? If it is, and we can't continue using it, we might want a json return. But otherwise I agree that an error is better

Comment (FelixJacobsen) [reply src/main/java/se/iths/crimedatabase/controller/AddressController.java:53]: Exceptions will not make the application shut down!

Comment (LordRekishi) [reply src/main/java/se/iths/crimedatabase/controller/AddressController.java:53]: Perfect!

**Review by LordRekishi — APPROVED** [review]
